{
 "title": "Computer Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Hardware Temps (C)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "node_hwmon_temp_celsius{}" }
   ]
  },
  {
   "title": "Node Local (avg/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    { "expr": "node_load1{}" }
   ]
  },
  {
   "title": "Hard Disk Free Space (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}"
    }
   ]
  }
 ]
}