{
 "title": "Twitch Bot",
 "description": "How is your Twitch bot doing?",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Friends in Chat",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bot_friends_total{}" }
   ]
  },
  {
   "title": "Bot Details Requested",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bot_details_total{}" }
   ]
  },
  {
   "title": "Hello Command",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bot_hello_total{}" }
   ]
  },
  {
   "title": "Visitors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 0 },
   "targets": [
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Github Link Requested",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bot_github_total{}" }
   ]
  },
  {
   "title": "Twitter Link Requested",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bot_twitter_total{}" }
   ]
  },
  {
   "title": "Processes - CPU Total (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    { "expr": "process_cpu_seconds_total{}" }
   ]
  },
  {
   "title": "Jaeger Traces",
   "type": "logs",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 18 },
   "targets": [
    { "operation": "Guestbook", "service": "botavio_kr-twitch" }
   ]
  }
 ]
}